// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="resolved-issues-2-9-0_{context}"]
= Resolved issues 2.9.0

.{project-short} enabled vTPM for source Windows Server 2022 virtual machines without vTPM device
VMware only: In earlier releases of {project-short}, after warm migration of Windows Server 2022 VMs with UEFI settings, the virtual Trusted Platform Module (vTPM) device was added to the VMs even though the source VMs did not have the vTPM device. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2014[(MTV-2014)]

.{project-short} failed to start virtual machine with non-aligned disk size after migration 
VMware only: In earlier releases of {project-short}, after migrating a VM with a disk size that did not align with the underlying storage, the VM failed to start. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2524[(MTV-2524)]

.{project-short} does not refer to incorrect URL in VDDK error message
When you created a VMware provider with an incorrect VDDK URL and then created a migration plan, the plan displayed a `VDDK init image invalid` error message without a reference to the incorrect URL. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-1150[(MTV-1150)]

.{project-short} swapped the MAC addresses after migrating VMware virtual machines with multiple NICs
In earlier releases of {project-short}, warm and cold migrations of a VMware VM with multiple network interface cards resulted in swapped MAC addresses for the NICs, if the order of network mapping were different in the migration plan than the network mappings in the source VM. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2025[(MTV-2025)]

.{project-short} failed OVA migration from unsupported source
In earlier releases of {project-short}, when you try to import Open Virtual Appliance (OVA) file from a non-VMware source, the import failed due to Megabytes unit not being supported for the resource. This issue has been resolved in 2.9.0 by adding a warning about OVA from an unsupported source.
link:https://issues.redhat.com/browse/MTV-2314[(MTV-2314)]

//resolved or known issue with a workaround? //from here it's all non support escalation bugs
.{project-short} does not fully preserve VMware virtual machine UUID after migration
In earlier releases of {project-short}, the UUID of VMware VMs were not fully preserved after migration to {ocp-short}. This issue has been resolved through a warning in migration plans to inform you that VM UUIDs are truncated to 20 characters for `virtio` disks. link:https://issues.redhat.com/browse/MTV-1368[(MTV-1368)]

.{project-short} does not preserve host name of guest virtual machines after migration
In earlier releases of {project-short}, after migrating a VMware guest VM running RHEL OS, the host name configured in the `/etc/hostname` setting was not preserved in the target VM. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2364[(MTV-2364)]

.Cold migration of VMware ESXi virtual machines with IP address fail
In earlier releases of {project-short}, cold migrations of ESXi VMs that were created with host IP address by using the vSphere provider failed because `virt-v2v` used the VM's host name instead of the IP address. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2153[(MTV-2153)]